[package]
name = "db_manager"
version = "0.1.0"
authors = ["limonadev <limonadev@whiteleaf.dev>"]
edition = "2018"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
